### PR TITLE
Refactor as Angular with components

### PR DESCRIPTION
**Pull request by ChuckIrvine**
Refactored as an Angular app with each example editor implemented as a component.

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
Thanks, will Check this in the next days :)

Am So., 20. Jan. 2019, 21:15 hat Chuck <notifications@github.com>
geschrieben:

**Comment by ChuckIrvine** [comment]
I see you merged in the reworked advanced example. There is a tiny bit of clean up to do on your main GitHub page. Something like:

1. Rename link to advanced example to something like “Advanced Angular Example”.
2. Rename link to simple example to something like “Simple Angular Example”.

-Chuck

**Comment by KillerCodeMonkey** [comment]
I know that… but first of all I have to clean up this repo and fix some stuff like gh pages and so on…
And after that I will change the main repo ;)

**Comment by KillerCodeMonkey** [comment]
So there was a lot of work to do. fixing examples and adding missing once.
I added stricter linting and removed unnecessary code.

Readded build and deploy to the ghpage

I also changed the readme of ngx-quill

**Comment by ChuckIrvine** [comment]
I’ve taken a look at the changes. Sorry, the code should have been cleaner. I think people will like it.

**Comment by KillerCodeMonkey** [comment]
No probs, thanks for your Initial Work!  IT triggered me to get this done :)

Am Di., 22. Jan. 2019, 20:13 hat Chuck <notifications@github.com>
geschrieben:

**Pull request merged**
